backend:
  name: github
  repo: oleg-danisin/newworldstandard
  branch: main

media_folder: "images/articles"
public_folder: "/images/articles"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Deck", name: "deck", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }